### PR TITLE
Italian Translation part 1

### PR DESCRIPTION
**Pull request by serhack**
Hello,
I'm your fan, I am a web developer and sysadmin. I would like if you can merge this pull about italian translation. Work in progress

### CODE REVIEW

**Comment by serhack** [comment]
if you want, you can merge :)

**Comment by anonimal** [comment]
Hi @serhack. This is fantastic, thank you very much for the translation.

I'm not able to merge this until you resolve merge conflicts (see the github error message). One way to is rebase (recommended).

Sidenote: in the future, I'd also recommend to work in a topic branch. https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging.

**Comment by serhack** [comment]
Hello anonimal, 
I noticied this issue, don't worry. I'm closing this pull as not resolved and I will open another :)
Thanks

**Comment by anonimal** [comment]
For future reference, you don't need to close a pull request to make changes after a rebase. Simply `git push --force` the branch (github will adjust accordingly).

**Pull request closed without merging**
